spring:

  main:
    web-application-type: none

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  datasource:
    url: jdbc:mysql://ec2-13-209-26-139.ap-northeast-2.compute.amazonaws.com:3306/catchup-dev?serverTimezone=UTC&autoReconnection=true
    username: root
    password: catchup!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      names: ${job.name:NONE}
logging:
  level:
    org.hibernate.SQL: debug
