spring:

  main:
    web-application-type: none

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 1000
    show-sql: false

  datasource:
    url: jdbc:mysql://ec2-3-35-17-62.ap-northeast-2.compute.amazonaws.com:3306/catchup-dev?serverTimezone=UTC&autoReconnection=true
    username: root
    password: habitbread!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      names: ${job.name:NONE}

logging:
  level:
    com.einschpanner.catchup.batch: debug
    org.springframework:
      batch.item.database: debug
    org.hibernate.SQL: debug
#    org.hibernate.type: trace