branch-defaults:
  master:
    environment: catch-up-dev
    group_suffix: null
deploy:
  artifact: build/libs/catch-up-0.0.1-SNAPSHOT.jar
global:
  application_name: catch-up
  branch: null
  default_ec2_keyname: awspwd
  default_platform: Java 8
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
