spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # MySQL logging

  datasource:
    url: jdbc:mysql://localhost:3306/catch-up?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gjlee7257
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

  output:
    ansi:
      enabled: always

logging:
  level:
    root: info