spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: false
        format_sql: true

  datasource:
    url: jdbc:mysql://ec2-13-209-26-139.ap-northeast-2.compute.amazonaws.com:3306/catchup-dev?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    username: root
    password: catchup!@
    driver-class-name: com.mysql.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    root: info