spring:
  profiles:
    include: oauth
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: false
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/catch-up?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gjlee7257
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

  output:
    ansi:
      enabled: always

logging:
  level:
    root: info