spring:
  profiles:
    include: oauth
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        format_sql: true

  datasource:
    url: jdbc:mysql://ec2-3-35-17-62.ap-northeast-2.compute.amazonaws.com:3306/catchup-dev?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    username: root
    password: habitbread!!
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    user:
#      name: admin
#      password: admin

logging:
  level:
    root: info